// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CountdownClockController from "./countdown_clock_controller"
application.register("countdown-clock", CountdownClockController)

import ExpandableController from "./expandable_controller"
application.register("expandable", ExpandableController)

import LocationFilterController from "./location_filter_controller"
application.register("location-filter", LocationFilterController)
