# Inherit the Rails Omakase defaults
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance

# Global settings
AllCops:
  UseCache: false
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'

Naming/VariableName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes